package com.example.triviaquiz.domain.questionDataTypes

enum class Category(val number:Int) {
    ANY_CATEGORY(0),
    GENERAL_KNOWLEDGE(1),
    ENTERTAINMENT_BOOKS(2),
    ENTERTAINMENT_FILM(3),
    ENTERTAINMENT_MUSIC(4),
    ENTERTAINMENT_MUSICALS(5),
    ENTERTAINMENT_TELEVISION(6),
    ENTERTAINMENT_VIDEO_GAMES(7),
    ENTERTAINMENT_BOARD_GAMES(8),
    SCIENCE_NATURE(9),
    SCIENCE_COMPUTERS(10),
    SCIENCE_MATHEMATICS(11),
    MYTHOLOGY(12),
    SPORTS(13),
    GEOGRAPHY(14),
    HISTORY(15),
    POLITICS(16),
    ART(17),
    CELEBRITIES(18),
    ANIMALS(19),
    VEHICLES(20),
    ENTERTAINMENT_COMICS(21),
    SCIENCE_GADGETS(22),
    ENTERTAINMENT_JAPANESE_ANIME(23),
    ENTERTAINMENT_CARTOON_ANIMATIONS(24)
}
